export enum ProductId {
  HOME = 'PRODUCT_HOME',
  COMMUNITY = 'PRODUCT_COMMUNITY',
  AI_CREATIONS = 'PRODUCT_AI_CREATIONS',
  MARKETPLACE = 'PRODUCT_MARKETPLACE'
}

export enum EcosystemId {
  FASHION_AI = 'ECOSYSTEM_GENERATE',
  CREATIVE_AI = 'ECOSYSTEM_CREATE',
  COMMERCE = 'PRODUCT_MARKETPLACE'
}

export enum EngineId {
  FASHION_AI_ENGINE = 'FashionAIEngine',
  CREATIVE_AI_ENGINE = 'CreativeAIEngine',
  COMMERCE_ENGINE = 'CommerceEngine',
  RECOMMENDATION_ENGINE = 'RecommendationEngine',
  MEMORY_ENGINE = 'MemoryEngine'
}

export enum ModuleId {
  SIDEBAR_WIDGETS = 'SidebarWidgets',
  TRENDING_PANEL = 'TrendingPanel',
  WARDROBE_PANEL = 'WardrobePanel',
  PLATFORM_LAUNCHER = 'PlatformEcosystemLauncher'
}

export enum NavigationId {
  HOME = 'HOME',
  PROFILE = 'PROFILE',
  AUTHENTICATION = 'AUTHENTICATION',
  AI_MEMORY = 'AI_MEMORY',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SEARCH = 'SEARCH',
  AI_ASSISTANT = 'AI_ASSISTANT',
  SETTINGS = 'SETTINGS'
}

export enum ProductIdentity {
  FACE_AI = 'FACE_AI',
  AI_CREATIONS = 'AI_CREATIONS',
  COMMUNITY = 'COMMUNITY',
  MARKETPLACE = 'MARKETPLACE',
  HOME_GENERATE = 'HOME_GENERATE'
}

export enum ProductStatus {
  INACTIVE = 'INACTIVE',
  INITIALIZING = 'INITIALIZING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  TERMINATED = 'TERMINATED'
}

export enum ProductCapabilities {
  FACE_UNDERSTANDING = 'FACE_UNDERSTANDING',
  BODY_MEASUREMENT = 'BODY_MEASUREMENT',
  CLOTHING_DRAPERY = 'CLOTHING_DRAPERY',
  VIRTUAL_TRY_ON = 'VIRTUAL_TRY_ON',
  MODEL_GENERATION = 'MODEL_GENERATION',
  PROMPT_TO_IMAGE = 'PROMPT_TO_IMAGE',
  SOCIAL_FEED = 'SOCIAL_FEED',
  CREATOR_ANALYTICS = 'CREATOR_ANALYTICS',
  DIGITAL_COMMERCE = 'DIGITAL_COMMERCE',
  PROMPT_MARKETPLACE = 'PROMPT_MARKETPLACE',
  REVENUE_SHARING = 'REVENUE_SHARING'
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write'
}
